"""Managed license base test suite"""

import semver

from license_manager_tests.base.license_manager_base_test_suite import LicenseManagerBaseTestSuite
from license_manager_tests.helpers.license_helper import LicenseHelper
from test_suites_core.base_test_suite import run_before_suite, run_after_suite


class ManagedLicenseBaseTestSuite(LicenseManagerBaseTestSuite):
    """License manager tests: managed license base test suite"""

    def _check_versions_eligible(self):
        """Check that test suite is compatible with ArangoDB versions that are being tested.
        If not, disable test suite.
        """
        if self.new_version is not None and semver.VersionInfo.parse(self.new_version) <= semver.VersionInfo.parse(
            "3.12.8"
        ):
            return False, "This test suite is only applicable to versions 3.12.8 and higher"
        else:
            return True, None

    @run_before_suite
    def download_operator_platform_tool(self):
        """ensure operator platform tool is available"""
        LicenseHelper.download_operator_platform_tool()

    @run_after_suite
    def cleanup(self):
        """remove files generated by managed license tests"""
        LicenseHelper.cleanup()
