"""Managed license base test suite"""

import semver

from license_manager_tests.base.license_manager_base_test_suite import LicenseManagerBaseTestSuite
from license_manager_tests.helpers.license_helper import LicenseHelper
from test_suites_core.base_test_suite import run_before_suite, run_after_suite

LM_TESTS_DIR = "lm_tests"


class ManagedLicenseBaseTestSuite(LicenseManagerBaseTestSuite):
    """License manager tests: managed license base test suite"""

    def _check_versions_eligible(self):
        """Check that test suite is compatible with ArangoDB versions that are being tested.
        If not, disable test suite.
        """
        if self.new_version is not None and semver.VersionInfo.parse(self.new_version) <= semver.VersionInfo.parse(
            "3.12.8"
        ):
            return False, "This test suite is only applicable to versions 3.12.8 and higher"
        else:
            return True, None

    def create_lm_tests_dir(self):
        """create directory for files generated by managed license tests"""
        self.lm_tests_dir = self.base_cfg.test_data_dir / LM_TESTS_DIR
        self.lm_tests_dir.mkdir(parents=False, exist_ok=True)

    @run_before_suite
    def download_operator_platform_tool(self):
        """ensure operator platform tool is available"""
        self.create_lm_tests_dir()
        LicenseHelper.download_operator_platform_tool(self.lm_tests_dir)

    @run_after_suite
    def cleanup(self):
        """remove files generated by managed license tests"""
        LicenseHelper.cleanup(self.lm_tests_dir)
